version: '3'
services:
  app:
    image: envios-internacionales-app
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - default
    volumes:
      - ./Wallet_BDBimestre1:/Wallet_BDBimestre1

networks:
  default:
   driver: bridge
